### ISSUE TITLE
Map view uses GPS coord over selecting a city 

### ISSUE THREAD

**Issue by zingelst** [social-torch/open311-mobile#9]
Not sure this is an issue, but it confused me a bit. The GPS in the emulator is set for Google Headquarters, and after selecting a city, the map view is shown, but it shows California. Not sure what I was expecting if I open the app in a remote city... but was a bit confusing.

**Comment by jpward** [comment]
App uses location of device which for simulator you will have to set to valid location via settings.  That being said this is a vaild bug still since the default location (if location services were turned off) will be a location in schenectady,ny which won't be valid for other cities.

Fix:
- derive default location from city name.

**Comment by jpward** [comment]
Default location is now derived from city if location services are not turned on:

https://github.com/social-torch/open311-mobile/commit/13407e041c48663bca29c32a80b1ecf14b628e1a
